def convert(country_name):
    if not country_name:
        return None
        
    # Dictionary mapping country names to FIPS10-4 codes
    # Extended mapping including additional countries and territories
    fips_mapping = {
        "afghanistan": "AF",
        "albania": "AL",
        "algeria": "AG",
        "american samoa": "AQ",
        "andorra": "AN",
        "angola": "AO",
        "anguilla": "AV",
        "antarctica": "AY",
        "antigua and barbuda": "AC",
        "argentina": "AR",
        "armenia": "AM",
        "aruba": "AA",
        "australia": "AS",
        "austria": "AU",
        "azerbaijan": "AJ",
        "bahamas": "BF",
        "bahrain": "BA",
        "bangladesh": "BG",
        "barbados": "BB",
        "belarus": "BO",
        "belgium": "BE",
        "belize": "BH",
        "benin": "BN",
        "bermuda": "BD",
        "bhutan": "BT",
        "bolivia": "BL",
        "bosnia and herzegovina": "BK",
        "botswana": "BC",
        "bouvet island": "BV",
        "brazil": "BR",
        "british indian ocean territory": "IO",
        "british virgin islands": "VI",
        "brunei": "BX",
        "bulgaria": "BU",
        "burkina faso": "UV",
        "burundi": "BY",
        "cambodia": "CB",
        "cameroon": "CM",
        "canada": "CA",
        "cape verde": "CV",
        "cayman islands": "CJ",
        "central african republic": "CT",
        "chad": "CD",
        "chile": "CI",
        "china": "CH",
        "christmas island": "KT",
        "cocos islands": "CK",
        "colombia": "CO",
        "comoros": "CN",
        "congo": "CF",
        "cook islands": "CW",
        "costa rica": "CS",
        "croatia": "HR",
        "cuba": "CU",
        "cyprus": "CY",
        "czech republic": "EZ",
        "denmark": "DA",
        "djibouti": "DJ",
        "dominica": "DO",
        "dominican republic": "DR",
        "east timor": "TT",
        "ecuador": "EC",
        "egypt": "EG",
        "el salvador": "ES",
        "equatorial guinea": "EK",
        "eritrea": "ER",
        "estonia": "EN",
        "ethiopia": "ET",
        "falkland islands": "FK",
        "faroe islands": "FO",
        "fiji": "FJ",
        "finland": "FI",
        "france": "FR",
        "french guiana": "FG",
        "french polynesia": "FP",
        "french southern territories": "FS",
        "gabon": "GB",
        "gambia": "GA",
        "georgia": "GG",
        "germany": "GM",
        "ghana": "GH",
        "gibraltar": "GI",
        "greece": "GR",
        "greenland": "GL",
        "grenada": "GJ",
        "guadeloupe": "GP",
        "guam": "GQ",
        "guatemala": "GT",
        "guernsey": "GK",
        "guinea": "GV",
        "guinea-bissau": "PU",
        "guyana": "GY",
        "haiti": "HA",
        "heard island and mcdonald islands": "HM",
        "honduras": "HO",
        "hong kong": "HK",
        "hungary": "HU",
        "iceland": "IC",
        "india": "IN",
        "indonesia": "ID",
        "iran": "IR",
        "iraq": "IZ",
        "ireland": "EI",
        "isle of man": "IM",
        "israel": "IS",
        "italy": "IT",
        "ivory coast": "IV",
        "jamaica": "JM",
        "japan": "JA",
        "jersey": "JE",
        "jordan": "JO",
        "kazakhstan": "KZ",
        "kenya": "KE",
        "kiribati": "KR",
        "kosovo": "KV",
        "kuwait": "KU",
        "kyrgyzstan": "KG",
        "laos": "LA",
        "latvia": "LG",
        "lebanon": "LE",
        "lesotho": "LT",
        "liberia": "LI",
        "libya": "LY",
        "liechtenstein": "LS",
        "lithuania": "LH",
        "luxembourg": "LU",
        "macau": "MC",
        "macedonia": "MK",
        "madagascar": "MA",
        "malawi": "MI",
        "malaysia": "MY",
        "maldives": "MV",
        "mali": "ML",
        "malta": "MT",
        "marshall islands": "RM",
        "martinique": "MB",
        "mauritania": "MR",
        "mauritius": "MP",
        "mayotte": "MF",
        "mexico": "MX",
        "micronesia": "FM",
        "moldova": "MD",
        "monaco": "MN",
        "mongolia": "MG",
        "montenegro": "MJ",
        "montserrat": "MH",
        "morocco": "MO",
        "mozambique": "MZ",
        "myanmar": "BM",
        "namibia": "WA",
        "nauru": "NR",
        "nepal": "NP",
        "netherlands": "NL",
        "netherlands antilles": "NT",
        "new caledonia": "NC",
        "new zealand": "NZ",
        "nicaragua": "NU",
        "niger": "NG",
        "nigeria": "NI",
        "niue": "NE",
        "norfolk island": "NF",
        "northern mariana islands": "CQ",
        "north korea": "KN",
        "norway": "NO",
        "oman": "MU",
        "pakistan": "PK",
        "palau": "PS",
        "palestine": "WE",
        "panama": "PM",
        "papua new guinea": "PP",
        "paraguay": "PA",
        "peru": "PE",
        "philippines": "RP",
        "pitcairn": "PC",
        "poland": "PL",
        "portugal": "PO",
        "puerto rico": "RQ",
        "qatar": "QA",
        "reunion": "RE",
        "romania": "RO",
        "russia": "RS",
        "rwanda": "RW",
        "saint barthelemy": "TB",
        "saint helena": "SH",
        "saint kitts and nevis": "SC",
        "saint lucia": "ST",
        "saint martin": "RN",
        "saint pierre and miquelon": "SB",
        "saint vincent and the grenadines": "VC",
        "samoa": "WS",
        "san marino": "SM",
        "sao tome and principe": "TP",
        "saudi arabia": "SA",
        "senegal": "SG",
        "serbia": "RI",
        "seychelles": "SE",
        "sierra leone": "SL",
        "singapore": "SN",
        "slovakia": "LO",
        "slovenia": "SI",
        "solomon islands": "BP",
        "somalia": "SO",
        "south africa": "SF",
        "south georgia and the south sandwich islands": "SX",
        "south korea": "KS",
        "south sudan": "OD",
        "spain": "SP",
        "sri lanka": "CE",
        "sudan": "SU",
        "suriname": "NS",
        "svalbard and jan mayen": "SV",
        "swaziland": "WZ",
        "sweden": "SW",
        "switzerland": "SZ",
        "syria": "SY",
        "taiwan": "TW",
        "tajikistan": "TI",
        "tanzania": "TZ",
        "thailand": "TH",
        "togo": "TO",
        "tokelau": "TL",
        "tonga": "TN",
        "trinidad and tobago": "TD",
        "tunisia": "TS",
        "turkey": "TU",
        "turkmenistan": "TX",
        "turks and caicos islands": "TK",
        "tuvalu": "TV",
        "uganda": "UG",
        "ukraine": "UP",
        "united arab emirates": "AE",
        "united kingdom": "UK",
        "united states": "US",
        "united states minor outlying islands": "UM",
        "uruguay": "UY",
        "uzbekistan": "UZ",
        "vanuatu": "NH",
        "vatican city": "VT",
        "venezuela": "VE",
        "vietnam": "VM",
        "wallis and futuna": "WF",
        "western sahara": "WI",
        "yemen": "YM",
        "zambia": "ZA",
        "zimbabwe": "ZI"
    }
    
    # 1. Try direct match (case-insensitive)
    country_name_lower = country_name.lower()
    if country_name_lower in fips_mapping:
        return fips_mapping[country_name_lower]
    
    # 2. Check for alternative names or partial matches
    # Common alternative names or abbreviations
    alt_names = {
        "united states of america": "US",
        "usa": "US",
        "america": "US",
        "u.s.": "US",
        "u.s.a.": "US",
        "uk": "UK",
        "britain": "UK",
        "great britain": "UK",
        "united kingdom of great britain and northern ireland": "UK",
        "russian federation": "RS",
        "uae": "AE",
        "côte d'ivoire": "IV",
        "cote d'ivoire": "IV",
        "democratic republic of congo": "CG",
        "dr congo": "CG",
        "drc": "CG",
        "republic of congo": "CF",
        "congo-brazzaville": "CF",
        "congo-kinshasa": "CG",
        "burma": "BM",
        "republic of korea": "KS",
        "democratic people's republic of korea": "KN",
        "dprk": "KN",
        "palestine state": "WE",
        "palestinian territories": "WE",
        "palestinian authority": "WE",
        "eswatini": "WZ",
        "czech republic": "EZ",
        "czechia": "EZ",
        "timor-leste": "TT",
        "vatican": "VT",
        "holy see": "VT",
        "hong kong sar": "HK",
        "macao sar": "MC",
        "macau sar": "MC",
        "channel islands": "JE",
        "tanzania, united republic of": "TZ",
        "viet nam": "VM",
        "republic of north macedonia": "MK",
        "republic of moldova": "MD",
        "saint vincent & the grenadines": "VC",
        "the bahamas": "BF",
        "gambia, the": "GA",
        "myanmar (burma)": "BM",
        "korea, south": "KS",
        "korea, north": "KN",
        "turkiye": "TU",
        "türkiye": "TU",
        "cape verde islands": "CV",
        "cabo verde": "CV"
    }
    
    if country_name_lower in alt_names:
        return alt_names[country_name_lower]
    
    # 3. Try to find a partial match
    for name, code in fips_mapping.items():
        if name in country_name_lower or country_name_lower in name:
            return code
    
    # 4. If no match is found
    return None

# # Example usage
# def main():
#     countries = ["United States", "Germany", "France", "Brazil", "India", 
#                 "China", "Russia", "Italy", "Spain", "Canada", 
#                 "United Kingdom", "Japan", "Australia", "Mexico", "South Korea",
#                 "Vatican City", "Puerto Rico", "Hong Kong", "Turks and Caicos", "Côte d'Ivoire"]
    
#     print("Country Codes (FIPS10-4):")
#     for country in countries:
#         code = convert(country)
#         if code is not None:
#             print(f"{country}: {code}")
#         else:
#             print(f"{country}: No FIPS code found")

# if __name__ == "__main__":
#     main()